### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by domachine** [domachine/penguin.js#1]
* [x] Make sure dev server doesn't crash on template syntax error
* [x] Render client in `pack` command
* [ ] Introduce website config to configure `assetPrefix` for the `pack` command
* [ ] Separate `build` into `penguin.js-core`
